### PR TITLE
[JBPM-9919] - Update PIM to use Quarkus 2.2.3

### PR DESCRIPTION
**Pull request by afalhambra**
**[JBPM-9919](https://issues.redhat.com/browse/JBPM-9919)**: Update PIM to use Quarkus 2.2.3

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]
lgtm

**Comment by mareknovotny** [comment]
please backport this to 7.59.x too to have community pipeline with this version too ;)

**Comment by afalhambra** [comment]
> please backport this to 7.59.x too to have community pipeline with this version too ;)

Thanks @mareknovotny - here it is https://github.com/kiegroup/process-migration-service/pull/29

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
ok, there is needed this PR https://github.com/kiegroup/droolsjbpm-integration/pull/2619 to be merged as upstream build fails in droolsjbpm-integration repository due jbpm change

**Comment by mareknovotny** [comment]
jenkins retest this please

**Pull request merged**
