### PR TITLE
[JBPM-9890] - PIM file generated name needs to be refactored

### PR DESCRIPTION
**Pull request by afalhambra**
**[JBPM-9890](https://issues.redhat.com/browse/JBPM-9890)**: PIM assembly file and name need some improvements

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

</details>

### CODE REVIEW

**Comment by afalhambra** [comment]
@mareknovotny - could you please merge along with its backport? thanks!

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
actually shouldn't be easier to remove `finalName` completely as by default the name of artifacts already does have that process-migration-service?

**Comment by afalhambra** [comment]
you're right, @mareknovotny - done, backport also updated now

**Comment by afalhambra** [comment]
@mareknovotny would you please merge this and its backport? thanks a lot again

**Pull request merged**
