### PR TITLE
upgraded to recent SNAPSHOT version

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

the version shoudl be synced with the recent version of all kie repos

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>

</details>

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by Ginxo** [comment]
this commit https://github.com/kiegroup/process-migration-service/pull/2/commits/8569cdbe671722a6c86907037375ff6c36ab9f29 should be cherry picked up if we want GA to be working

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
> this commit [8569cdb](https://github.com/kiegroup/process-migration-service/commit/8569cdbe671722a6c86907037375ff6c36ab9f29) should be cherry picked up if we want GA to be working

i thought it is already on main branch, so simple rebase should help not cherry-pick, what do I miss? @Ginxo

**Pull request merged**
