### PR TITLE
[7.67.x][RHPAM-4470] sanitize sorting columns

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_

[RHPAM-4470](https://issues.redhat.com/browse/RHPAM-4470)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/process-migration-service/pull/73

### CODE REVIEW

**Review by afalhambra — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by lazarotti** [comment]
Jenkins retest this

**Pull request merged**
