### PR TITLE
[RHPAM-4465] Add quarkus-file-vault-utils instructions and support

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

**Thank you for submitting this pull request**

**JIRA**:

[RHPAM-4465](https://issues.redhat.com/browse/RHPAM-4465)

### CODE REVIEW

**Review by afalhambra — COMMENTED** [review]
I think it would be worth adding some instructions in the README.md file about how to mask the keystore password by using this new feature

@mareknovotny not sure if requires any change from your side, since PIM will bundled a new component as part of the build

**Comment by mareknovotny** [comment]
cc @Ginxo @rgdoliveira

**Comment by ruromero** [comment]
FYI this is still a draft because I created https://github.com/quarkiverse/quarkus-file-vault/pull/36
and in case it is not merged/accepted we will have to find a different way of include it in our distributable.
Depending on how the linked PR is resolved I will update the docs accordingly.

**Comment by ruromero** [comment]
I have updated the docs even though the linked PR is not accepted but we can change them later

**Comment by ruromero** [comment]
@mareknovotny ready for review

**Review by afalhambra — APPROVED** [review]
great work @ruromero!

**Comment by mareknovotny** [comment]
even this change for upstream is ok, we can't proceed the backport until Quarkus vault extension is in downstream supported too. So we can merge or hold on until this is resolved and be able to back port it to 7.67.x branches.

**Comment by lazarotti** [comment]
@mareknovotny I discussed this Jira with Ivo and it can be merged. The Quarkus File Vault is already Tech-Preview since 7.13: https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.13/html/release_notes_for_red_hat_process_automation_manager_7.13/rn-tech-preview-con#support_for_quarkiverse_file_vault_and_keystore_files_with_the_process_instance_migration_keystore_vault

The scope of this Jira is to upgrade the extension version for this component in tech preview to 0.7.1, which will allow customers to use the encryption functionality of the quarkus file vault, if they are interested to. If this will be supported or not should be treated in Support Exception Jiras, but for the general TP it is ok.

**Comment by mareknovotny** [comment]
please don't forget on backporting to 7.67.x and 7.67.x-blue branches ;)

**Pull request merged**
